### PR TITLE
Evan optimise communication

### PR DESCRIPTION
**Pull request by evanpacini**
### Description

> Added error handling, the use of promises, fixed many types, optimised as much code as I could. Probably a masterpiece.

### CODE REVIEW

**Review by KaspervanM — CHANGES_REQUESTED** [review]
It is looking very nice, but there are some things that still can be changed. see PR #80 for my request.

Also, why put the error banner to the right of the screen at the dashboard? That is **NOT** looking good:
image

**Comment by evanpacini** [comment]
I added a Promise system to evaluateCode and added error handling.

**Review by KaspervanM — CHANGES_REQUESTED** [review]
It is looking absolutely fantastic. I like those toast boxes.
There were only two major things that came to mind when reviewing:

1. The names of interfaces and types: They are not the same everywhere.
2. The taskloop: It is too big and barely readable.

To solve these things I made #81. Take a look and tell me what you think. Did I misunderstand anything or mis anything? Tell me.

**Review by KaspervanM — APPROVED** [review]
I approve.

**Pull request merged**
